# Generated by Django 6.0.4 on 2026-04-18 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyClubuser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='First name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email address')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Venue name')),
                ('address', models.CharField(max_length=100, verbose_name='Venue address')),
                ('zip_code', models.CharField(max_length=15, verbose_name='zip code')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='contact phone')),
                ('web', models.URLField(blank=True, verbose_name='website address')),
                ('email_address', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event name')),
                ('event_date', models.DateTimeField(verbose_name='Event date and time')),
                ('manager', models.CharField(max_length=60, verbose_name='Event manager')),
                ('description', models.TextField(blank=True, verbose_name='Event description')),
                ('attendees', models.ManyToManyField(blank=True, to='clubweb.myclubuser')),
                ('venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubweb.venue')),
            ],
        ),
    ]
