# Generated by Django 4.2.30 on 2026-04-19 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clubweb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Event name')),
                ('event_date', models.DateTimeField(verbose_name='Event date and time')),
                ('manager', models.CharField(max_length=60, verbose_name='Event manager')),
                ('description', models.TextField(blank=True, verbose_name='Event description')),
            ],
        ),
        migrations.AlterField(
            model_name='myclubuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='venue',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.DeleteModel(
            name='clubweb',
        ),
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='clubweb.venue'),
        ),
    ]
